repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.0  # Specify the desired version
    hooks:
      - id: clang-format
        files: ^(DentrixUI/|DentrixCore/|main\.cpp)$  # Only match files in these directories or main.cpp
        exclude: ^(third_party/)  # Optional: exclude third-party files or directories

