@startuml





/' Objects '/

class GLWidget {
	+GLWidget(QWidget* parent, std::string path, int jaw_index)
	+~GLWidget()
	-brush : Brush
	-currentBrushMode : BrushMode
	-camera : Camera
	-toothGizmo : Gizmo*
	-selectedGizmoComponent : GizmoComponent*
	-selectedMesh : Mesh*
	#editScene : Scene
	#mainScene : Scene
	#currentScene : Scene*
	-shader : Shader*
	-areArchesAligned : bool
	-ctrlHeld : bool
	-freeDeformAddMode : bool
	#inMainScene : bool
	-isDraggingGizmo : bool
	-isGizmoEnabled : bool
	-isLowerJawSelected : bool
	-isRotating : bool
	-isUpperJawSelected : bool
	+lowerJawLoaded : bool
	-shiftHeld : bool
	+upperJawLoaded : bool
	-gizmoModelMatrix : glm::mat4
	-model : glm::mat4
	-projection : glm::mat4
	-view : glm::mat4
	-lowerJawCenter : glm::vec3
	-upperJawCenter : glm::vec3
	-jaw_index : int
	-mousePosX : int
	-mousePosY : int
	-lowerArch : mcg::Arch
	-upperArch : mcg::Arch
	-lowerJawUnsegmented : pmp::SurfaceMesh
	-upperJawUnsegmented : pmp::SurfaceMesh
	-meshSelectedInMainScene() : signals : void
	-initialFilePath : std::string
	-lowerJawLabelsPath : std::string
	-upperJawLabelsPath : std::string
	+lowerJawMeshes : std::vector<Mesh*>
	-meshes : std::vector<Mesh*>
	+upperJawMeshes : std::vector<Mesh*>
	-lowerRemap : std::vector<pmp::Face>
	-upperRemap : std::vector<pmp::Face>
	+applyArchAlignResult(const ArchAlignData& result) : void
	+applyLowerJawResult(const JawLoadResult& result) : void
	+applyUpperJawResult(const JawLoadResult& result) : void
	+archAlign() : void
	+archAlignAsync() : void
	#initializeGL() : void
	+keyPressEvent(QKeyEvent* event) : void
	+keyReleaseEvent(QKeyEvent* event) : void
	+loadLowerJaw(const std::string& path) : void
	+loadLowerJawAsync(const QString& path) : void
	+loadModel(const std::string& path) : void
	+loadUpperJaw(const std::string& path) : void
	+loadUpperJawAsync(const QString& path) : void
	#mouseMoveEvent(QMouseEvent* event) : void
	#mousePressEvent(QMouseEvent* event) : void
	#mouseReleaseEvent(QMouseEvent* event) : void
	-movedToEditScene() : void
	-movedToMainScene() : void
	+onEditSceneClicked() : void
	+onResetJawClicked() : void
	+onToolChange() : void
	#paintGL() : void
	+rebuildMainScene() : void
	#resizeGL(int w, int h) : void
	+rotateMesh() : void
	-saveEditSceneAndReturnToMainScene() : void
	+setBrushSize(int value) : void
	+setDeformationStrength(int value) : void
	+setFreeDeformAddMode(bool isAdd) : void
	+setSelectedMeshDirectionalScale(int val, bool xActive, bool yActive, bool zActive) : void
	+setSelectedMeshRotationAngle(int rotationAngleDegrees) : void
	+setSelectedMeshScale(int scale) : void
	+updateCursor() : void
	+updateMeshScale() : void
	#wheelEvent(QWheelEvent* event) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml

